name: Build Aplication and Push Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Obteniendo Codigo Fuente
        uses: actions/checkout@v3

      - name: Instalando Node v22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalando Dependencias
        run: npm install
  
      - name: Configurando Ambiente
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' > ./.env

      - name: Migrando base de datos a Prisma Postgres
        run: |
          npx prisma migrate deploy

      - name: Conectando a la base de datos
        run: |
          npx prisma generate --no-engine

      - name: Compilando la aplicación
        run: |
          npm run build

      - name:  Obteniendo Version
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Configurando Docker
        uses: docker/setup-buildx-action@v2

      - name: Login Repositorio Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --push -f Dockerfile \
            -t markitooo/saturn_dedsec_cl:${{ env.VERSION }} .
